#pragma once
#include <torch/torch.h>
#include <opencv2/opencv.hpp>
#include <iostream>
#include <filesystem>
#include <vector>
#include <string>
#include <random>
#include <map>
#include <fstream>
#include <algorithm>
#include <jpeglib.h>
#include <stdlib.h>